package me.devanshj.covid19widget

val locations = listOf(
    AppWidgetState.Location("IN", "India"),
    AppWidgetState.Location("IN-MH", "Maharashtra, India"),
    AppWidgetState.Location("IN-TN", "Tamil Nadu, India"),
    AppWidgetState.Location("IN-DL", "Delhi, India"),
    AppWidgetState.Location("IN-KL", "Kerala, India"),
    AppWidgetState.Location("IN-TG", "Telangana, India"),
    AppWidgetState.Location("IN-UP", "Uttar Pradesh, India"),
    AppWidgetState.Location("IN-RJ", "Rajasthan, India"),
    AppWidgetState.Location("IN-AP", "Andhra Pradesh, India"),
    AppWidgetState.Location("IN-MP", "Madhya Pradesh, India"),
    AppWidgetState.Location("IN-KA", "Karnataka, India"),
    AppWidgetState.Location("IN-GJ", "Gujarat, India"),
    AppWidgetState.Location("IN-JK", "Jammu and Kashmir, India"),
    AppWidgetState.Location("IN-HR", "Haryana, India"),
    AppWidgetState.Location("IN-PB", "Punjab, India"),
    AppWidgetState.Location("IN-WB", "West Bengal, India"),
    AppWidgetState.Location("IN-BR", "Bihar, India"),
    AppWidgetState.Location("IN-AS", "Assam, India"),
    AppWidgetState.Location("IN-UT", "Uttarakhand, India"),
    AppWidgetState.Location("IN-OR", "Odisha, India"),
    AppWidgetState.Location("IN-CH", "Chandigarh, India"),
    AppWidgetState.Location("IN-LA", "Ladakh, India"),
    AppWidgetState.Location("IN-AN", "Andaman and Nicobar Islands, India"),
    AppWidgetState.Location("IN-CT", "Chhattisgarh, India"),
    AppWidgetState.Location("IN-GA", "Goa, India"),
    AppWidgetState.Location("IN-HP", "Himachal Pradesh, India"),
    AppWidgetState.Location("IN-PY", "Puducherry, India"),
    AppWidgetState.Location("IN-JH", "Jharkhand, India"),
    AppWidgetState.Location("IN-MN", "Manipur, India"),
    AppWidgetState.Location("IN-MZ", "Mizoram, India"),
    AppWidgetState.Location("IN-AR", "Arunachal Pradesh, India"),
    AppWidgetState.Location("IN-DN", "Dadra and Nagar Haveli, India"),
    AppWidgetState.Location("IN-DD", "Daman and Diu, India"),
    AppWidgetState.Location("IN-LD", "Lakshadweep, India"),
    AppWidgetState.Location("IN-ML", "Meghalaya, India"),
    AppWidgetState.Location("IN-NL", "Nagaland, India"),
    AppWidgetState.Location("IN-SK", "Sikkim, India"),
    AppWidgetState.Location("IN-TR", "Tripura, India")
)